name: Automatic PR
on:
  push:
    branches: ["develop"]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: PR demo
          body: Auto-created Pull Request
          branch: ${{ github.ref }}
          base: main